#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath -s $0))
cd "$SCRIPT_PATH"

trap ctrl_c INT TERM 

function ctrl_c {
	echo "Terminating punchpress simulator ..."
}


echo "Starting punchpress simulator ..."
insmod mods/pruss.ko 
insmod mods/spi_slave.ko
insmod mods/sim.ko

rm -f /dev/ppsim0

major=`awk "\\$2==\"simulator\" {print \\$1}" /proc/devices`
mknod /dev/ppsim0 c $major 0
chmod 664 /dev/ppsim0

while [ ! -c /dev/ttyGS0 ]; do sleep 1; done

visserver/visserver 

rmmod sim spi_slave pruss
rm -f /dev/ppsim0

echo "Punchpress simulator terminated"

