#!/bin/sh

# Oracle Java 8 is required because of the JavaFX dependency
JAVA=/usr/java/latest/bin/java

CLASSPATH='-cp ./jssc.jar:./javax.json-1.0.4.jar:.'

$JAVA $CLASSPATH bpv.view.Visualizer "$@"

